[[constraint]]
  branch = "v1"
  name = "github.com/Masterminds/squirrel"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/gomemcache"

[[constraint]]
  name = "github.com/cznic/ql"
  version = "1.1.0"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.6.2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  revision = "00e2b89d8ad42af22b20fdb9adfbbfa0d5f34660"

[[constraint]]
  branch = "master"
  name = "github.com/golang/gddo"

[[constraint]]
  name = "github.com/google/go-github"
  revision = "dfd20fd7fa6edec56447fcb049acd5e17a78ec2e"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/heroku/docker-registry-client"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattes/migrate"
  revision = "ce1b59bb819416ca67422929b1cb48bb342720b6"

[[constraint]]
  name = "github.com/nats-io/nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/common"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/go-checkpoint"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
