[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  revision = "00e2b89d8ad42af22b20fdb9adfbbfa0d5f34660"

[[constraint]]
  name = "github.com/google/go-github"
  revision = "dfd20fd7fa6edec56447fcb049acd5e17a78ec2e"

[[constraint]]
  name = "github.com/mattes/migrate"
  revision = "ce1b59bb819416ca67422929b1cb48bb342720b6"

[[constraint]]
  name = "github.com/gorilla/mux"
  revision = "780415097119f6f61c55475fe59b66f3c3e9ea53"

[[constraint]]
  name = "github.com/heroku/docker-registry-client"
  source = "https://github.com/paulbellamy/docker-registry-client.git"
  branch = "handle-relative-nextlinks"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
