{{- if .Values.helmOperator.tls.enable -}}
{{- if .Values.helmOperator.tls.verify -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flux.fullname" . }}-helm-tls-ca-config
data:
  ca.crt: {{ .Values.helmOperator.tls.caContent }}
{{- end -}}
{{- end -}}
