version: 2
jobs:
  build:
    working_directory: /go/src/github.com/weaveworks/flux
    docker:
      - image: circleci/golang:1.8
      - image: nats
      - image: memcached
    steps:
      - checkout
      - setup_remote_docker

      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: make test TEST_FLAGS="-race -tags integration -timeout 30s"
      - run: make all

      - deploy:
          name: Maybe push master images
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              for IMAGE in flux flux-service; do
                docker push "quay.io/weaveworks/$IMAGE:$(docker/image-tag)"
              done
            fi

      - deploy:
          name: Maybe push release images and upload binaries
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "^[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              go get github.com/weaveworks/github-release
              make release-bins
              bin/upload-binaries
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              for IMAGE in flux flux-service; do
                docker push "quay.io/weaveworks/$IMAGE:$(docker/image-tag)"
              done
            fi
