apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxy-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxy-database
    spec:
      containers:
      - name: postgres
        image: postgres:9.5
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
  - port: 5432
  selector:
    name: database
