apiVersion: v1
appVersion: "1.3.1"
description: Flux is a tool that automatically ensures that the state of a cluster matches what is specified in version control
name: flux
version: 0.1.0
home: https://weave.works
sources:
- https://github.com/weaveworks/flux
maintainers:
  - name: stefanprodan
    email: stefan@weave.works
engine: gotpl
icon: https://landscape.cncf.io/logos/flux.svg
